services:

  # ===== LAZYSYSADMIN ====
  lazysysadmin:
    build:
      context: ./LazySysAdmin_1/LazySysAdmin/
      dockerfile: Dockerfile
    container_name: lazysysadmin
    restart: unless-stopped
    ports:
      - "8085:8085"
    mem_limit: 512m
    cpus: 0.5
    read_only: false
    networks:
      - lazysysadmin_net

networks:
  lazysysadmin_net:
    driver: bridge
